name: CI Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Initialize CodeQL
        id: init_codeql
        uses: github/codeql-action/init@v1
        with:
          queries: security-and-quality

      - name: Autobuild
        id: auto_build 
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        id: analyze_codeql
        uses: github/codeql-action/analyze@v1